### ISSUE TITLE
pw-front-svelte/bin/build.sh exports YT_API_KEY instead of PUBLIC_YT_API_KEY

### ISSUE THREAD

**Issue by mulpdev** [rbarisic-lme/pal-dash#7]
Exported variable name is `YT_API_KEY` but which crashes build of pw-front because it expects `PUBLIC_YT_API_KEY` to be exported

See: https://github.com/rbarisic-lme/pal-dash/blob/main/pw-front-svelte/bin/build.sh#L28

**Comment by rbarisic-lme** [comment]
thx for the info, should be fixed with aa52851
